//Constants for adding expenses
export const ADD_EXPENSE_REQUESTED="ADD_EXPENSE_REQUESTED";
export const ADD_EXPENSE_SUCCESS="ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_FAILED="ADD_EXPENSE_FAILED"
export const RESET_EXPENSE="RESET_EXPENSE"
//constants for getting transactions
export const GET_TRANSACTIONS_REQUESTED="GET_TRANSACTIONS_REQUESTED";
export const GET_TRANSACTIONS_SUCCESS="GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILED="GET_TRANSACTIONS_FAILED";


